# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g @angular/cli@9.1.1
    ng build --prod
    INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id E1PDWZPR0W2KAS --paths '/*' | jq '.Invalidation | .Id' | cut -d \" -f2)
    aws cloudfront wait invalidation-completed --id $INVALIDATION_ID --distribution-id E1PDWZPR0W2KAS
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: drop
    pathtoPublish: 'dist'
    displayName: 'Publish Artifacts'